### ISSUE TITLE
DECFLOAT values and format:decimal

### ISSUE THREAD

**Issue by ralfhandl** [SAP/openapi-specification#6]
The definition of [`x-sap-precision`](https://github.com/SAP/openapi-specification/tree/main/sap-schemas/v3.0#x-sap-precision) shows it use for a `DECFLOAT34` value in combination with `format:decimal`.

However the [OpenAPI format registration for `decimal`](https://spec.openapis.org/registry/format/decimal.html) states that

> The `decimal` format represents a **fixed** point decimal number of unspecified precision and range.

Should we instead use the [newly registered OpenAPI format `decimal128`](https://spec.openapis.org/registry/format/decimal128.html) for `DECFLOAT34` values?

**Comment by swennemers** [comment]
Hi Ralf,
to be honest, I don't have a stake in this type and don't know the history.
Best regards
Sebastian
